"""
    Parcours Doctoral API

    This API delivers data for the Parcours Doctoral project.  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_parcours_doctoral_sdk
from osis_parcours_doctoral_sdk.model.modifier_cotutelle_command import ModifierCotutelleCommand


class TestModifierCotutelleCommand(unittest.TestCase):
    """ModifierCotutelleCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModifierCotutelleCommand(self):
        """Test ModifierCotutelleCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModifierCotutelleCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
