"""
    Parcours Doctoral API

    This API delivers data for the Parcours Doctoral project.  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_parcours_doctoral_sdk
from osis_parcours_doctoral_sdk.model.choix_type_epreuve import ChoixTypeEpreuve


class TestChoixTypeEpreuve(unittest.TestCase):
    """ChoixTypeEpreuve unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChoixTypeEpreuve(self):
        """Test ChoixTypeEpreuve"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ChoixTypeEpreuve()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
