"""
    Parcours Doctoral API

    This API delivers data for the Parcours Doctoral project.  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


import unittest

import osis_parcours_doctoral_sdk
from osis_parcours_doctoral_sdk.api.doctorate_api import DoctorateApi  # noqa: E501


class TestDoctorateApi(unittest.TestCase):
    """DoctorateApi unit test stubs"""

    def setUp(self):
        self.api = DoctorateApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_assent_training(self):
        """Test case for assent_training

        """
        pass

    def test_complete_confirmation_paper_by_promoter(self):
        """Test case for complete_confirmation_paper_by_promoter

        """
        pass

    def test_create_doctoral_training(self):
        """Test case for create_doctoral_training

        """
        pass

    def test_create_jury_members(self):
        """Test case for create_jury_members

        """
        pass

    def test_destroy_training(self):
        """Test case for destroy_training

        """
        pass

    def test_list_complementary_training(self):
        """Test case for list_complementary_training

        """
        pass

    def test_list_course_enrollment(self):
        """Test case for list_course_enrollment

        """
        pass

    def test_list_doctoral_training(self):
        """Test case for list_doctoral_training

        """
        pass

    def test_list_doctorates(self):
        """Test case for list_doctorates

        """
        pass

    def test_list_jury_members(self):
        """Test case for list_jury_members

        """
        pass

    def test_list_supervised_doctorates(self):
        """Test case for list_supervised_doctorates

        """
        pass

    def test_remove_jury_member(self):
        """Test case for remove_jury_member

        """
        pass

    def test_retrieve_confirmation_papers(self):
        """Test case for retrieve_confirmation_papers

        """
        pass

    def test_retrieve_cotutelle(self):
        """Test case for retrieve_cotutelle

        """
        pass

    def test_retrieve_dashboard(self):
        """Test case for retrieve_dashboard

        """
        pass

    def test_retrieve_doctoral_training_config(self):
        """Test case for retrieve_doctoral_training_config

        """
        pass

    def test_retrieve_external_doctorate_supervision(self):
        """Test case for retrieve_external_doctorate_supervision

        """
        pass

    def test_retrieve_funding(self):
        """Test case for retrieve_funding

        """
        pass

    def test_retrieve_jury_member(self):
        """Test case for retrieve_jury_member

        """
        pass

    def test_retrieve_jury_preparation(self):
        """Test case for retrieve_jury_preparation

        """
        pass

    def test_retrieve_last_confirmation_paper(self):
        """Test case for retrieve_last_confirmation_paper

        """
        pass

    def test_retrieve_last_confirmation_paper_canvas(self):
        """Test case for retrieve_last_confirmation_paper_canvas

        """
        pass

    def test_retrieve_parcours_doctoral_dto(self):
        """Test case for retrieve_parcours_doctoral_dto

        """
        pass

    def test_retrieve_project(self):
        """Test case for retrieve_project

        """
        pass

    def test_retrieve_supervision(self):
        """Test case for retrieve_supervision

        """
        pass

    def test_retrieve_training(self):
        """Test case for retrieve_training

        """
        pass

    def test_submit_confirmation_paper(self):
        """Test case for submit_confirmation_paper

        """
        pass

    def test_submit_confirmation_paper_extension_request(self):
        """Test case for submit_confirmation_paper_extension_request

        """
        pass

    def test_submit_training(self):
        """Test case for submit_training

        """
        pass

    def test_update_cotutelle(self):
        """Test case for update_cotutelle

        """
        pass

    def test_update_funding(self):
        """Test case for update_funding

        """
        pass

    def test_update_jury_member(self):
        """Test case for update_jury_member

        """
        pass

    def test_update_jury_preparation(self):
        """Test case for update_jury_preparation

        """
        pass

    def test_update_role_jury_member(self):
        """Test case for update_role_jury_member

        """
        pass

    def test_update_training(self):
        """Test case for update_training

        """
        pass


if __name__ == '__main__':
    unittest.main()
