"""
    Parcours Doctoral API

    This API delivers data for the Parcours Doctoral project.  # noqa: E501

    The version of the OpenAPI document: 1.0.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_parcours_doctoral_sdk
from osis_parcours_doctoral_sdk.model.categorie_activite import CategorieActivite


class TestCategorieActivite(unittest.TestCase):
    """CategorieActivite unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCategorieActivite(self):
        """Test CategorieActivite"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CategorieActivite()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
