"""
    Parcours Doctoral API

    This API delivers data for the Parcours Doctoral project.  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Generated by: https://openapi-generator.tech
"""


import unittest

import osis_parcours_doctoral_sdk
from osis_parcours_doctoral_sdk.api.references_api import ReferencesApi  # noqa: E501


class TestReferencesApi(unittest.TestCase):
    """ReferencesApi unit test stubs"""

    def setUp(self):
        self.api = ReferencesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_retrieve_scholarship(self):
        """Test case for retrieve_scholarship

        """
        pass


if __name__ == '__main__':
    unittest.main()
