"""
    Parcours Doctoral API

    This API delivers data for the Parcours Doctoral project.  # noqa: E501

    The version of the OpenAPI document: 1.0.4
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_parcours_doctoral_sdk
from osis_parcours_doctoral_sdk.model.parcours_doctoral_recherche_dto_formation_entite_gestion import ParcoursDoctoralRechercheDTOFormationEntiteGestion


class TestParcoursDoctoralRechercheDTOFormationEntiteGestion(unittest.TestCase):
    """ParcoursDoctoralRechercheDTOFormationEntiteGestion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParcoursDoctoralRechercheDTOFormationEntiteGestion(self):
        """Test ParcoursDoctoralRechercheDTOFormationEntiteGestion"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ParcoursDoctoralRechercheDTOFormationEntiteGestion()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
