"""
    Parcours Doctoral API

    This API delivers data for the Parcours Doctoral project.  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_parcours_doctoral_sdk
from osis_parcours_doctoral_sdk.model.scholarship import Scholarship


class TestScholarship(unittest.TestCase):
    """Scholarship unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScholarship(self):
        """Test Scholarship"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Scholarship()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
