"""
    Parcours Doctoral API

    This API delivers data for the Parcours Doctoral project.  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_parcours_doctoral_sdk
from osis_parcours_doctoral_sdk.model.parcours_doctoral_dto_projet import ParcoursDoctoralDTOProjet


class TestParcoursDoctoralDTOProjet(unittest.TestCase):
    """ParcoursDoctoralDTOProjet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParcoursDoctoralDTOProjet(self):
        """Test ParcoursDoctoralDTOProjet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ParcoursDoctoralDTOProjet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
