"""
    Parcours Doctoral API

    This API delivers data for the Parcours Doctoral project.  # noqa: E501

    The version of the OpenAPI document: 1.0.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_parcours_doctoral_sdk
from osis_parcours_doctoral_sdk.model.action_link import ActionLink
globals()['ActionLink'] = ActionLink
from osis_parcours_doctoral_sdk.model.parcours_doctoral_recherche_dto_links import ParcoursDoctoralRechercheDTOLinks


class TestParcoursDoctoralRechercheDTOLinks(unittest.TestCase):
    """ParcoursDoctoralRechercheDTOLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParcoursDoctoralRechercheDTOLinks(self):
        """Test ParcoursDoctoralRechercheDTOLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ParcoursDoctoralRechercheDTOLinks()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
