"""
    Parcours Doctoral API

    This API delivers data for the Parcours Doctoral project.  # noqa: E501

    The version of the OpenAPI document: 1.0.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_parcours_doctoral_sdk
from osis_parcours_doctoral_sdk.model.modifier_role_membre_command import ModifierRoleMembreCommand


class TestModifierRoleMembreCommand(unittest.TestCase):
    """ModifierRoleMembreCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModifierRoleMembreCommand(self):
        """Test ModifierRoleMembreCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModifierRoleMembreCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
