"""
    Parcours Doctoral API

    This API delivers data for the Parcours Doctoral project.  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_parcours_doctoral_sdk
from osis_parcours_doctoral_sdk.model.parcours_doctoral_recherche_dto_formation import ParcoursDoctoralRechercheDTOFormation
from osis_parcours_doctoral_sdk.model.parcours_doctoral_recherche_dto_links import ParcoursDoctoralRechercheDTOLinks
globals()['ParcoursDoctoralRechercheDTOFormation'] = ParcoursDoctoralRechercheDTOFormation
globals()['ParcoursDoctoralRechercheDTOLinks'] = ParcoursDoctoralRechercheDTOLinks
from osis_parcours_doctoral_sdk.model.parcours_doctoral_recherche_dto import ParcoursDoctoralRechercheDTO


class TestParcoursDoctoralRechercheDTO(unittest.TestCase):
    """ParcoursDoctoralRechercheDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParcoursDoctoralRechercheDTO(self):
        """Test ParcoursDoctoralRechercheDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ParcoursDoctoralRechercheDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
