"""
    Parcours Doctoral API

    This API delivers data for the Parcours Doctoral project.  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_parcours_doctoral_sdk
from osis_parcours_doctoral_sdk.model.parcours_doctoral_dto_financement_bourse_recherche import ParcoursDoctoralDTOFinancementBourseRecherche
globals()['ParcoursDoctoralDTOFinancementBourseRecherche'] = ParcoursDoctoralDTOFinancementBourseRecherche
from osis_parcours_doctoral_sdk.model.parcours_doctoral_dto_financement import ParcoursDoctoralDTOFinancement


class TestParcoursDoctoralDTOFinancement(unittest.TestCase):
    """ParcoursDoctoralDTOFinancement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParcoursDoctoralDTOFinancement(self):
        """Test ParcoursDoctoralDTOFinancement"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ParcoursDoctoralDTOFinancement()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
