"""
    Parcours Doctoral API

    This API delivers data for the Parcours Doctoral project.  # noqa: E501

    The version of the OpenAPI document: 1.0.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_parcours_doctoral_sdk
from osis_parcours_doctoral_sdk.model.action_link import ActionLink
globals()['ActionLink'] = ActionLink
from osis_parcours_doctoral_sdk.model.parcours_doctoral_dto_links import ParcoursDoctoralDTOLinks


class TestParcoursDoctoralDTOLinks(unittest.TestCase):
    """ParcoursDoctoralDTOLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParcoursDoctoralDTOLinks(self):
        """Test ParcoursDoctoralDTOLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ParcoursDoctoralDTOLinks()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
