"""
    Parcours Doctoral API

    This API delivers data for the Parcours Doctoral project.  # noqa: E501

    The version of the OpenAPI document: 1.0.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_parcours_doctoral_sdk
from osis_parcours_doctoral_sdk.model.parcours_doctoral_dto_financement_bourse_recherche import ParcoursDoctoralDTOFinancementBourseRecherche


class TestParcoursDoctoralDTOFinancementBourseRecherche(unittest.TestCase):
    """ParcoursDoctoralDTOFinancementBourseRecherche unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParcoursDoctoralDTOFinancementBourseRecherche(self):
        """Test ParcoursDoctoralDTOFinancementBourseRecherche"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ParcoursDoctoralDTOFinancementBourseRecherche()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
