"""
    Parcours Doctoral API

    This API delivers data for the Parcours Doctoral project.  # noqa: E501

    The version of the OpenAPI document: 1.0.6
    Generated by: https://openapi-generator.tech
"""


import unittest

import osis_parcours_doctoral_sdk
from osis_parcours_doctoral_sdk.api.autocomplete_api import AutocompleteApi  # noqa: E501


class TestAutocompleteApi(unittest.TestCase):
    """AutocompleteApi unit test stubs"""

    def setUp(self):
        self.api = AutocompleteApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_people(self):
        """Test case for list_people

        """
        pass

    def test_list_tutors(self):
        """Test case for list_tutors

        """
        pass


if __name__ == '__main__':
    unittest.main()
