"""
    Parcours Doctoral API

    This API delivers data for the Parcours Doctoral project.  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_parcours_doctoral_sdk
from osis_parcours_doctoral_sdk.model.categorie_activite import CategorieActivite
from osis_parcours_doctoral_sdk.model.choix_type_epreuve import ChoixTypeEpreuve
from osis_parcours_doctoral_sdk.model.communication import Communication
from osis_parcours_doctoral_sdk.model.conference import Conference
from osis_parcours_doctoral_sdk.model.conference_communication import ConferenceCommunication
from osis_parcours_doctoral_sdk.model.conference_publication import ConferencePublication
from osis_parcours_doctoral_sdk.model.contexte_formation import ContexteFormation
from osis_parcours_doctoral_sdk.model.course import Course
from osis_parcours_doctoral_sdk.model.paper import Paper
from osis_parcours_doctoral_sdk.model.publication import Publication
from osis_parcours_doctoral_sdk.model.residency import Residency
from osis_parcours_doctoral_sdk.model.residency_communication import ResidencyCommunication
from osis_parcours_doctoral_sdk.model.seminar import Seminar
from osis_parcours_doctoral_sdk.model.seminar_communication import SeminarCommunication
from osis_parcours_doctoral_sdk.model.service import Service
from osis_parcours_doctoral_sdk.model.statut_activite import StatutActivite
from osis_parcours_doctoral_sdk.model.ucl_course import UclCourse
from osis_parcours_doctoral_sdk.model.valorisation import Valorisation
globals()['CategorieActivite'] = CategorieActivite
globals()['ChoixTypeEpreuve'] = ChoixTypeEpreuve
globals()['Communication'] = Communication
globals()['Conference'] = Conference
globals()['ConferenceCommunication'] = ConferenceCommunication
globals()['ConferencePublication'] = ConferencePublication
globals()['ContexteFormation'] = ContexteFormation
globals()['Course'] = Course
globals()['Paper'] = Paper
globals()['Publication'] = Publication
globals()['Residency'] = Residency
globals()['ResidencyCommunication'] = ResidencyCommunication
globals()['Seminar'] = Seminar
globals()['SeminarCommunication'] = SeminarCommunication
globals()['Service'] = Service
globals()['StatutActivite'] = StatutActivite
globals()['UclCourse'] = UclCourse
globals()['Valorisation'] = Valorisation
from osis_parcours_doctoral_sdk.model.doctoral_training_activity import DoctoralTrainingActivity


class TestDoctoralTrainingActivity(unittest.TestCase):
    """DoctoralTrainingActivity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDoctoralTrainingActivity(self):
        """Test DoctoralTrainingActivity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DoctoralTrainingActivity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
