"""
    Parcours Doctoral API

    This API delivers data for the Parcours Doctoral project.  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_parcours_doctoral_sdk
from osis_parcours_doctoral_sdk.model.external_supervision_dto_parcours_doctoral_projet import ExternalSupervisionDTOParcoursDoctoralProjet
from osis_parcours_doctoral_sdk.model.parcours_doctoral_recherche_dto_formation import ParcoursDoctoralRechercheDTOFormation
globals()['ExternalSupervisionDTOParcoursDoctoralProjet'] = ExternalSupervisionDTOParcoursDoctoralProjet
globals()['ParcoursDoctoralRechercheDTOFormation'] = ParcoursDoctoralRechercheDTOFormation
from osis_parcours_doctoral_sdk.model.external_supervision_dto_parcours_doctoral import ExternalSupervisionDTOParcoursDoctoral


class TestExternalSupervisionDTOParcoursDoctoral(unittest.TestCase):
    """ExternalSupervisionDTOParcoursDoctoral unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExternalSupervisionDTOParcoursDoctoral(self):
        """Test ExternalSupervisionDTOParcoursDoctoral"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ExternalSupervisionDTOParcoursDoctoral()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
