"""
    Parcours Doctoral API

    This API delivers data for the Parcours Doctoral project.  # noqa: E501

    The version of the OpenAPI document: 1.0.3
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from osis_parcours_doctoral_sdk.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from osis_parcours_doctoral_sdk.exceptions import ApiAttributeError


def lazy_import():
    from osis_parcours_doctoral_sdk.model.categorie_activite import CategorieActivite
    from osis_parcours_doctoral_sdk.model.contexte_formation import ContexteFormation
    from osis_parcours_doctoral_sdk.model.statut_activite import StatutActivite
    globals()['CategorieActivite'] = CategorieActivite
    globals()['ContexteFormation'] = ContexteFormation
    globals()['StatutActivite'] = StatutActivite


class ConferencePublication(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('publication_status',): {
            'None': None,
            'EMPTY': "",
            'UNSUBMITTED': "UNSUBMITTED",
            'SUBMITTED': "SUBMITTED",
            'IN_REVIEW': "IN_REVIEW",
            'ACCEPTED': "ACCEPTED",
            'PUBLISHED': "PUBLISHED",
        },
        ('committee',): {
            'None': None,
            'EMPTY': "",
            'YES': "YES",
            'NO': "NO",
            'NA': "NA",
        },
    }

    validations = {
        ('ects',): {
            'inclusive_minimum': 0,
        },
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'object_type': (str,),  # noqa: E501
            'category': (CategorieActivite,),  # noqa: E501
            'context': (ContexteFormation,),  # noqa: E501
            'type': (str,),  # noqa: E501
            'ects': (float, none_type,),  # noqa: E501
            'title': (str,),  # noqa: E501
            'start_date': (date, none_type,),  # noqa: E501
            'publication_status': (str, none_type,),  # noqa: E501
            'authors': (str,),  # noqa: E501
            'role': (str,),  # noqa: E501
            'keywords': (str,),  # noqa: E501
            'committee': (str, none_type,),  # noqa: E501
            'journal': (str,),  # noqa: E501
            'dial_reference': (str,),  # noqa: E501
            'comment': (str,),  # noqa: E501
            'parent': (str,),  # noqa: E501
            'uuid': (str,),  # noqa: E501
            'status': (StatutActivite,),  # noqa: E501
            'parcours_doctoral': (int,),  # noqa: E501
            'reference_promoter_assent': (bool, none_type,),  # noqa: E501
            'reference_promoter_comment': (str,),  # noqa: E501
            'cdd_comment': (str,),  # noqa: E501
            'can_be_submitted': (bool,),  # noqa: E501
            'summary': ([str],),  # noqa: E501
            'acceptation_proof': ([str],),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'object_type': 'object_type',  # noqa: E501
        'category': 'category',  # noqa: E501
        'context': 'context',  # noqa: E501
        'type': 'type',  # noqa: E501
        'ects': 'ects',  # noqa: E501
        'title': 'title',  # noqa: E501
        'start_date': 'start_date',  # noqa: E501
        'publication_status': 'publication_status',  # noqa: E501
        'authors': 'authors',  # noqa: E501
        'role': 'role',  # noqa: E501
        'keywords': 'keywords',  # noqa: E501
        'committee': 'committee',  # noqa: E501
        'journal': 'journal',  # noqa: E501
        'dial_reference': 'dial_reference',  # noqa: E501
        'comment': 'comment',  # noqa: E501
        'parent': 'parent',  # noqa: E501
        'uuid': 'uuid',  # noqa: E501
        'status': 'status',  # noqa: E501
        'parcours_doctoral': 'parcours_doctoral',  # noqa: E501
        'reference_promoter_assent': 'reference_promoter_assent',  # noqa: E501
        'reference_promoter_comment': 'reference_promoter_comment',  # noqa: E501
        'cdd_comment': 'cdd_comment',  # noqa: E501
        'can_be_submitted': 'can_be_submitted',  # noqa: E501
        'summary': 'summary',  # noqa: E501
        'acceptation_proof': 'acceptation_proof',  # noqa: E501
    }

    read_only_vars = {
        'uuid',  # noqa: E501
        'reference_promoter_assent',  # noqa: E501
        'reference_promoter_comment',  # noqa: E501
        'cdd_comment',  # noqa: E501
        'can_be_submitted',  # noqa: E501
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, object_type, category, context, type, ects, title, start_date, publication_status, authors, role, keywords, committee, journal, dial_reference, comment, parent, *args, **kwargs):  # noqa: E501
        """ConferencePublication - a model defined in OpenAPI

        Args:
            object_type (str):
            category (CategorieActivite):
            context (ContexteFormation):
            type (str):
            ects (float, none_type):
            title (str):
            start_date (date, none_type):
            publication_status (str, none_type):
            authors (str):
            role (str):
            keywords (str):
            committee (str, none_type):
            journal (str):
            dial_reference (str):
            comment (str):
            parent (str):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            uuid (str): [optional]  # noqa: E501
            status (StatutActivite): [optional]  # noqa: E501
            parcours_doctoral (int): [optional]  # noqa: E501
            reference_promoter_assent (bool, none_type): [optional]  # noqa: E501
            reference_promoter_comment (str): [optional]  # noqa: E501
            cdd_comment (str): [optional]  # noqa: E501
            can_be_submitted (bool): [optional]  # noqa: E501
            summary ([str]): [optional]  # noqa: E501
            acceptation_proof ([str]): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.object_type = object_type
        self.category = category
        self.context = context
        self.type = type
        self.ects = ects
        self.title = title
        self.start_date = start_date
        self.publication_status = publication_status
        self.authors = authors
        self.role = role
        self.keywords = keywords
        self.committee = committee
        self.journal = journal
        self.dial_reference = dial_reference
        self.comment = comment
        self.parent = parent
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, object_type, category, context, type, ects, title, start_date, publication_status, authors, role, keywords, committee, journal, dial_reference, comment, parent, *args, **kwargs):  # noqa: E501
        """ConferencePublication - a model defined in OpenAPI

        Args:
            object_type (str):
            category (CategorieActivite):
            context (ContexteFormation):
            type (str):
            ects (float, none_type):
            title (str):
            start_date (date, none_type):
            publication_status (str, none_type):
            authors (str):
            role (str):
            keywords (str):
            committee (str, none_type):
            journal (str):
            dial_reference (str):
            comment (str):
            parent (str):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            uuid (str): [optional]  # noqa: E501
            status (StatutActivite): [optional]  # noqa: E501
            parcours_doctoral (int): [optional]  # noqa: E501
            reference_promoter_assent (bool, none_type): [optional]  # noqa: E501
            reference_promoter_comment (str): [optional]  # noqa: E501
            cdd_comment (str): [optional]  # noqa: E501
            can_be_submitted (bool): [optional]  # noqa: E501
            summary ([str]): [optional]  # noqa: E501
            acceptation_proof ([str]): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.object_type = object_type
        self.category = category
        self.context = context
        self.type = type
        self.ects = ects
        self.title = title
        self.start_date = start_date
        self.publication_status = publication_status
        self.authors = authors
        self.role = role
        self.keywords = keywords
        self.committee = committee
        self.journal = journal
        self.dial_reference = dial_reference
        self.comment = comment
        self.parent = parent
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
