# flake8: noqa

"""
    Parcours Doctoral API

    This API delivers data for the Parcours Doctoral project.  # noqa: E501

    The version of the OpenAPI document: 1.0.4
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.4"

# import ApiClient
from osis_parcours_doctoral_sdk.api_client import ApiClient

# import Configuration
from osis_parcours_doctoral_sdk.configuration import Configuration

# import exceptions
from osis_parcours_doctoral_sdk.exceptions import OpenApiException
from osis_parcours_doctoral_sdk.exceptions import ApiAttributeError
from osis_parcours_doctoral_sdk.exceptions import ApiTypeError
from osis_parcours_doctoral_sdk.exceptions import ApiValueError
from osis_parcours_doctoral_sdk.exceptions import ApiKeyError
from osis_parcours_doctoral_sdk.exceptions import ApiException
